name: Update README
on:
  push:
    branches:
      - main
jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: muesli/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git config --global user.name "readme-scribe 🤖"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update generated README"
          git push
